name: Build with PyInstaller

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        
        strategy:
            matrix:
                os: [ windows-latest, macos-latest, ubuntu-latest ]
                python-version: [ 3.11 ]
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            -   name: Build with PyInstaller
                run: |
                    if [ ${{ matrix.os }} == 'windows-latest' ]; then
                      pyinstaller --onefile --name counter_phisher.exe counter_phisher.py
                    elif [ ${{ matrix.os }} == 'macos-latest' ]; then
                      pyinstaller --onefile --name counter_phisher.app counter_phisher.py
                    elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
                      pyinstaller --onefile --name counter_phisher counter_phisher.py
                    else
                      echo "Unsupported OS"
                      exit 1
                    fi
            -   name: Upload artifact
                uses: actions/upload-artifact@v2
                with:
                    name: counter_phisher
                    path: dist/counter_phisher